### ISSUE TITLE
PL/1 vs RPG , how can be done ?

### ISSUE THREAD

**Issue by openmax** [christianlarsen/dynamicarray#1]
Hi Christian , 

this is reference for PL/I language -> https://www.ibm.com/docs/en/SSY2V3_5.1.0/com.ibm.ent.pl1.zos.doc/lrm.pdf
languange where i mastering very well pointer .. 

What i don't know how to do in RPG is list processing like this code in PL/I , 
where i can reference direct the value pointed by pointer :  (Pag 283 of the pdf linked ) 

```
dcl 1 STR based(H),
         2 P pointer,
         2 data CHAR(100),
T pointer;
allocate STR;
T=H;
do loop;
  allocate STR set(T->P);
  T=T->P;
  T->P=null;
end;
```

the magic in PL/I is "->"  so in RPG something like this :  
```
**free

dcl-s H pointer template;
dcl-ds STR qualified template;
    data varchar(100) inz;
    P like(STR) inz;
end-ds;

dcl-s T pointer;
dcl-s array like(STR);

H=%alloc(%size(array));
T=H;
doW found;
  T->P=%alloc(%size(array));
  T=T->P;
  T->P=*null;
  ..
  ..
  ..
enddo;
```

how can be done or it can be done ?  (   in  c/c++ we have similar behavior .. )
Thanks You.

**Comment by christianlarsen** [comment]
Hi!

The "->" is the way some languages identify pointers. Thus, if you indicate "-> *NULL" it is the same as if you say that you want the pointer to have the value *NULL.

In the case of RPG, this symbol is not used. The pointer is another field, which has that type: "pointer".

In the dynamic array, in the procedure **DYN_retrieveNode** , I use a loop to recover a node, where I go through the array using the pointers:
```
     ptr_aux = array;
     z = 1;
     dow z <= number;
         if z = number;
             return node_aux.text;
         endif;
         z += 1;
         ptr_aux = node_aux.ptrnext;
     enddo;
```

In this case, when I do:

`ptr_aux = node_aux.ptrnet`

It would be something similar to:

`ptr_aux = node_aux -> ptrnet`

I don't know if this will clarify your doubts.

**Comment by openmax** [comment]
Hi , 

thanks for the rapid response
but no, doubts remain .. 

in PLI   if i want to refer in elgant way to the value of next item on list and change the value , i can do :  
  
if H<>NULL
  if H->STR.P<>NULL 
    if ( H->STR.P->STR.data == "Hello") ;
       H->STR.P->STR.data = "Bye";
 
as you can see non need of loop or aux pointer . 

the good is also the i can indicate the data structure to use with pointer too ..

if ( h->str.p->newds.previous->oldds.data == "Hello"  )

the rpg way is ugly IMO ..
 
in case of double linked list for example , i can use a pointer to iterate back e forward in the list like : 

cursor = first_of_list;
cursor = cursor->LIST.next ;

or 

cursor = last_of_list;
cursor = cursor->LIST.prev;

and check value of the data structure : 

cursor.LIST.data = 'HELLO'

This is in C -> https://www.programiz.com/dsa/doubly-linked-list 
and is very similar , i cannot find same on RPG ... 

i hope i better explain my doubts

**Comment by christianlarsen** [comment]
That can't be done like that in RPG, as far as I know.
